name: AKS Deployment


on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v2
      
      
    
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
    # The Go version to download (if necessary) and use. Supports semver spec and ranges.
         go-version: 1.18.2
    # Path to the go.mod or go.work file.
      
      
      - name: go build
      
        run: go build -c release
        
      - name: docker build
        run: docker build -t employee-api
        
      - name: docker login
        run: docker login --username '${{secrets.docker_login}}' --password '${{secrets.docker_password}}
        
      - name: tag docker image
        run: docker tag employee-api '${{secrets.docker_login}}'/employee-api:'${{BUILD_NUMBER}}'
        
        
      - name: push docker image
        run: docker push '${{secrets.docker_login}}'/employee-api:'${{BUILD_NUMBER}}'
      
      
